
package ru.gosuslugi.dom.schema.integration.bills_service_async;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "BillsServiceAsync", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/bills-service-async/", wsdlLocation = "http://localhost/")
public class BillsServiceAsync
    extends Service
{

    private static final URL BILLSSERVICEASYNC_WSDL_LOCATION;
    private static final WebServiceException BILLSSERVICEASYNC_EXCEPTION;
    private static final QName BILLSSERVICEASYNC_QNAME = new QName("http://dom.gosuslugi.ru/schema/integration/bills-service-async/", "BillsServiceAsync");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BILLSSERVICEASYNC_WSDL_LOCATION = url;
        BILLSSERVICEASYNC_EXCEPTION = e;
    }

    public BillsServiceAsync() {
        super(__getWsdlLocation(), BILLSSERVICEASYNC_QNAME);
    }

    public BillsServiceAsync(WebServiceFeature... features) {
        super(__getWsdlLocation(), BILLSSERVICEASYNC_QNAME, features);
    }

    public BillsServiceAsync(URL wsdlLocation) {
        super(wsdlLocation, BILLSSERVICEASYNC_QNAME);
    }

    public BillsServiceAsync(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BILLSSERVICEASYNC_QNAME, features);
    }

    public BillsServiceAsync(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BillsServiceAsync(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BillsPortsTypeAsync
     */
    @WebEndpoint(name = "BillsPortAsync")
    public BillsPortsTypeAsync getBillsPortAsync() {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/bills-service-async/", "BillsPortAsync"), BillsPortsTypeAsync.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BillsPortsTypeAsync
     */
    @WebEndpoint(name = "BillsPortAsync")
    public BillsPortsTypeAsync getBillsPortAsync(WebServiceFeature... features) {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/bills-service-async/", "BillsPortAsync"), BillsPortsTypeAsync.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BILLSSERVICEASYNC_EXCEPTION!= null) {
            throw BILLSSERVICEASYNC_EXCEPTION;
        }
        return BILLSSERVICEASYNC_WSDL_LOCATION;
    }

}
