
package ru.gosuslugi.dom.schema.integration.fas_service_async;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "FASServiceAsync", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/fas-service-async/", wsdlLocation = "http://localhost/")
public class FASServiceAsync
    extends Service
{

    private static final URL FASSERVICEASYNC_WSDL_LOCATION;
    private static final WebServiceException FASSERVICEASYNC_EXCEPTION;
    private static final QName FASSERVICEASYNC_QNAME = new QName("http://dom.gosuslugi.ru/schema/integration/fas-service-async/", "FASServiceAsync");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FASSERVICEASYNC_WSDL_LOCATION = url;
        FASSERVICEASYNC_EXCEPTION = e;
    }

    public FASServiceAsync() {
        super(__getWsdlLocation(), FASSERVICEASYNC_QNAME);
    }

    public FASServiceAsync(WebServiceFeature... features) {
        super(__getWsdlLocation(), FASSERVICEASYNC_QNAME, features);
    }

    public FASServiceAsync(URL wsdlLocation) {
        super(wsdlLocation, FASSERVICEASYNC_QNAME);
    }

    public FASServiceAsync(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FASSERVICEASYNC_QNAME, features);
    }

    public FASServiceAsync(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FASServiceAsync(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FASPortsTypeAsync
     */
    @WebEndpoint(name = "FASPortAsync")
    public FASPortsTypeAsync getFASPortAsync() {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/fas-service-async/", "FASPortAsync"), FASPortsTypeAsync.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FASPortsTypeAsync
     */
    @WebEndpoint(name = "FASPortAsync")
    public FASPortsTypeAsync getFASPortAsync(WebServiceFeature... features) {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/fas-service-async/", "FASPortAsync"), FASPortsTypeAsync.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FASSERVICEASYNC_EXCEPTION!= null) {
            throw FASSERVICEASYNC_EXCEPTION;
        }
        return FASSERVICEASYNC_WSDL_LOCATION;
    }

}
