
package ru.gosuslugi.dom.schema.integration.nsi_common_service_async;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * Асинхронный сервис экспорта общих справочников подсистемы НСИ
 * 
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "NsiServiceAsync", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/nsi-common-service-async/", wsdlLocation = "http://localhost/")
public class NsiServiceAsync
    extends Service
{

    private static final URL NSISERVICEASYNC_WSDL_LOCATION;
    private static final WebServiceException NSISERVICEASYNC_EXCEPTION;
    private static final QName NSISERVICEASYNC_QNAME = new QName("http://dom.gosuslugi.ru/schema/integration/nsi-common-service-async/", "NsiServiceAsync");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NSISERVICEASYNC_WSDL_LOCATION = url;
        NSISERVICEASYNC_EXCEPTION = e;
    }

    public NsiServiceAsync() {
        super(__getWsdlLocation(), NSISERVICEASYNC_QNAME);
    }

    public NsiServiceAsync(WebServiceFeature... features) {
        super(__getWsdlLocation(), NSISERVICEASYNC_QNAME, features);
    }

    public NsiServiceAsync(URL wsdlLocation) {
        super(wsdlLocation, NSISERVICEASYNC_QNAME);
    }

    public NsiServiceAsync(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NSISERVICEASYNC_QNAME, features);
    }

    public NsiServiceAsync(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NsiServiceAsync(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NsiPortsTypeAsync
     */
    @WebEndpoint(name = "NsiPortAsync")
    public NsiPortsTypeAsync getNsiPortAsync() {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/nsi-common-service-async/", "NsiPortAsync"), NsiPortsTypeAsync.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NsiPortsTypeAsync
     */
    @WebEndpoint(name = "NsiPortAsync")
    public NsiPortsTypeAsync getNsiPortAsync(WebServiceFeature... features) {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/nsi-common-service-async/", "NsiPortAsync"), NsiPortsTypeAsync.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NSISERVICEASYNC_EXCEPTION!= null) {
            throw NSISERVICEASYNC_EXCEPTION;
        }
        return NSISERVICEASYNC_WSDL_LOCATION;
    }

}
