
package ru.gosuslugi.dom.schema.integration.house_management_service_async;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * Сервис управления объектами РАО
 * 
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "HouseManagementServiceAsync", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/house-management-service-async/", wsdlLocation = "http://localhost/")
public class HouseManagementServiceAsync
    extends Service
{

    private static final URL HOUSEMANAGEMENTSERVICEASYNC_WSDL_LOCATION;
    private static final WebServiceException HOUSEMANAGEMENTSERVICEASYNC_EXCEPTION;
    private static final QName HOUSEMANAGEMENTSERVICEASYNC_QNAME = new QName("http://dom.gosuslugi.ru/schema/integration/house-management-service-async/", "HouseManagementServiceAsync");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOUSEMANAGEMENTSERVICEASYNC_WSDL_LOCATION = url;
        HOUSEMANAGEMENTSERVICEASYNC_EXCEPTION = e;
    }

    public HouseManagementServiceAsync() {
        super(__getWsdlLocation(), HOUSEMANAGEMENTSERVICEASYNC_QNAME);
    }

    public HouseManagementServiceAsync(WebServiceFeature... features) {
        super(__getWsdlLocation(), HOUSEMANAGEMENTSERVICEASYNC_QNAME, features);
    }

    public HouseManagementServiceAsync(URL wsdlLocation) {
        super(wsdlLocation, HOUSEMANAGEMENTSERVICEASYNC_QNAME);
    }

    public HouseManagementServiceAsync(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HOUSEMANAGEMENTSERVICEASYNC_QNAME, features);
    }

    public HouseManagementServiceAsync(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HouseManagementServiceAsync(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HouseManagementPortsTypeAsync
     */
    @WebEndpoint(name = "HouseManagementPortAsync")
    public HouseManagementPortsTypeAsync getHouseManagementPortAsync() {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/house-management-service-async/", "HouseManagementPortAsync"), HouseManagementPortsTypeAsync.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HouseManagementPortsTypeAsync
     */
    @WebEndpoint(name = "HouseManagementPortAsync")
    public HouseManagementPortsTypeAsync getHouseManagementPortAsync(WebServiceFeature... features) {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/house-management-service-async/", "HouseManagementPortAsync"), HouseManagementPortsTypeAsync.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOUSEMANAGEMENTSERVICEASYNC_EXCEPTION!= null) {
            throw HOUSEMANAGEMENTSERVICEASYNC_EXCEPTION;
        }
        return HOUSEMANAGEMENTSERVICEASYNC_WSDL_LOCATION;
    }

}
