
package ru.gosuslugi.dom.schema.integration.drs_service_async;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * Сервис управления запросами о наличии задолженности за ЖКУ
 * 
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "DebtRequestsServiceAsync", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/drs-service-async", wsdlLocation = "http://localhost/")
public class DebtRequestsServiceAsync
    extends Service
{

    private static final URL DEBTREQUESTSSERVICEASYNC_WSDL_LOCATION;
    private static final WebServiceException DEBTREQUESTSSERVICEASYNC_EXCEPTION;
    private static final QName DEBTREQUESTSSERVICEASYNC_QNAME = new QName("http://dom.gosuslugi.ru/schema/integration/drs-service-async", "DebtRequestsServiceAsync");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DEBTREQUESTSSERVICEASYNC_WSDL_LOCATION = url;
        DEBTREQUESTSSERVICEASYNC_EXCEPTION = e;
    }

    public DebtRequestsServiceAsync() {
        super(__getWsdlLocation(), DEBTREQUESTSSERVICEASYNC_QNAME);
    }

    public DebtRequestsServiceAsync(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEBTREQUESTSSERVICEASYNC_QNAME, features);
    }

    public DebtRequestsServiceAsync(URL wsdlLocation) {
        super(wsdlLocation, DEBTREQUESTSSERVICEASYNC_QNAME);
    }

    public DebtRequestsServiceAsync(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEBTREQUESTSSERVICEASYNC_QNAME, features);
    }

    public DebtRequestsServiceAsync(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DebtRequestsServiceAsync(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DebtRequestsAsyncPort
     */
    @WebEndpoint(name = "DebtRequestsAsyncPort")
    public DebtRequestsAsyncPort getDebtRequestsAsyncPort() {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/drs-service-async", "DebtRequestsAsyncPort"), DebtRequestsAsyncPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DebtRequestsAsyncPort
     */
    @WebEndpoint(name = "DebtRequestsAsyncPort")
    public DebtRequestsAsyncPort getDebtRequestsAsyncPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/drs-service-async", "DebtRequestsAsyncPort"), DebtRequestsAsyncPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEBTREQUESTSSERVICEASYNC_EXCEPTION!= null) {
            throw DEBTREQUESTSSERVICEASYNC_EXCEPTION;
        }
        return DEBTREQUESTSSERVICEASYNC_WSDL_LOCATION;
    }

}
