
package ru.gosuslugi.dom.schema.integration.drs_service_async;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import ru.gosuslugi.dom.schema.integration.base.AckRequest;
import ru.gosuslugi.dom.schema.integration.base.GetStateRequest;
import ru.gosuslugi.dom.schema.integration.drs.ExportDRsRequest;
import ru.gosuslugi.dom.schema.integration.drs.ExportDSRsRequest;
import ru.gosuslugi.dom.schema.integration.drs.GetStateResult;
import ru.gosuslugi.dom.schema.integration.drs.ImportDRsRequest;
import ru.gosuslugi.dom.schema.integration.drs.ImportDSRResponsesRequest;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "DebtRequestsAsyncPort", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/drs-service-async")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration.drs.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.nsi_base.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class
})
public interface DebtRequestsAsyncPort {


    /**
     * Загрузка в ГИС ЖКХ запросов о наличии задолженности за ЖКУ (организациями, направляющими запросы)
     * 
     * @param importDRsRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importDebtRequests")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "importDRsResult")
    public AckRequest importDebtRequests(
        @WebParam(name = "importDRsRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/drs/", partName = "importDRsRequest")
        ImportDRsRequest importDRsRequest)
        throws Fault
    ;

    /**
     * Выгрузка из ГИС ЖКХ подзапросов о наличии задолженности за ЖКУ (организациями, предоставляющими ЖКУ)
     * 
     * @param exportDSRsRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportDebtSubrequests")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "exportDSRsResult")
    public AckRequest exportDebtSubrequests(
        @WebParam(name = "exportDSRsRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/drs/", partName = "exportDSRsRequest")
        ExportDSRsRequest exportDSRsRequest)
        throws Fault
    ;

    /**
     * Загрузка в ГИС ЖКХ ответов на запросы о наличии задолженности за ЖКУ (организациями, предоставляющими ЖКУ)
     * 
     * @param importDSRsRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importResponses")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "importDSRsResult")
    public AckRequest importResponses(
        @WebParam(name = "importDSRResponsesRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/drs/", partName = "importDSRsRequest")
        ImportDSRResponsesRequest importDSRsRequest)
        throws Fault
    ;

    /**
     * Выгрузка из ГИС ЖКХ запросов о наличии задолженности за ЖКУ (организациями, направляющими запросы)
     * 
     * @param exportDRsRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportDebtRequests")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "exportDRsResult")
    public AckRequest exportDebtRequests(
        @WebParam(name = "exportDRsRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/drs/", partName = "exportDRsRequest")
        ExportDRsRequest exportDRsRequest)
        throws Fault
    ;

    /**
     * Результат обработки асинхронного вызова
     * 
     * @param getStateRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.drs.GetStateResult
     * @throws Fault
     */
    @WebMethod(action = "urn:getState")
    @WebResult(name = "getStateResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/drs/", partName = "getStateResult")
    public GetStateResult getState(
        @WebParam(name = "getStateRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "getStateRequest")
        GetStateRequest getStateRequest)
        throws Fault
    ;

}
