
package ru.gosuslugi.dom.schema.integration.drs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import ru.gosuslugi.dom.schema.integration.base.AttachmentType;
import ru.gosuslugi.dom.schema.integration.base.Period;


/**
 * Данные подзапроса о наличии задолженности за ЖКУ, сформированного ГИС ЖКХ
 * 
 * <p>Java class for DSRType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="DSRType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="subrequestGUID" type="{http://dom.gosuslugi.ru/schema/integration/base/}GUIDType"/>
 *         <element name="requestInfo">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="requestGUID" type="{http://dom.gosuslugi.ru/schema/integration/base/}GUIDType"/>
 *                   <element name="requestNumber" type="{http://dom.gosuslugi.ru/schema/integration/drs/}RequestNumberType"/>
 *                   <element name="organization" type="{http://dom.gosuslugi.ru/schema/integration/drs/}OrganizationInfoType"/>
 *                   <element name="housingFundObject" type="{http://dom.gosuslugi.ru/schema/integration/drs/}ExportHousingFundObjectInfoType"/>
 *                   <element name="period" type="{http://dom.gosuslugi.ru/schema/integration/base/}Period"/>
 *                   <element name="status" type="{http://dom.gosuslugi.ru/schema/integration/drs/}RequestStatusType"/>
 *                   <element name="sentDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   <element name="responseDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   <element name="executorInfo" type="{http://dom.gosuslugi.ru/schema/integration/drs/}ExecutorInfoType"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="responseStatus" type="{http://dom.gosuslugi.ru/schema/integration/drs/}ResponseStatusType"/>
 *         <element name="responseData" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="hasDebt" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   <element name="debtInfo" type="{http://dom.gosuslugi.ru/schema/integration/drs/}ExportDebtInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *                   <element name="additionalFile" type="{http://dom.gosuslugi.ru/schema/integration/base/}AttachmentType" maxOccurs="unbounded" minOccurs="0"/>
 *                   <element name="description" minOccurs="0">
 *                     <simpleType>
 *                       <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         <maxLength value="1000"/>
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                   <element name="executorInfo" type="{http://dom.gosuslugi.ru/schema/integration/drs/}ExecutorInfoType"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DSRType", propOrder = {
    "subrequestGUID",
    "requestInfo",
    "responseStatus",
    "responseData"
})
public class DSRType {

    /**
     * Идентификатор подзапроса, присвоенный в ГИС ЖКХ
     * 
     */
    @XmlElement(required = true)
    protected String subrequestGUID;
    /**
     * Информация об исходном запросе в ГИС ЖКХ о наличии задолженности за ЖКУ
     * 
     */
    @XmlElement(required = true)
    protected DSRType.RequestInfo requestInfo;
    /**
     * Статус ответа на подзапрос о наличии задолженности за ЖКУ.
     * 
     * 						Допустимые значения:
     * 						NotSent - Не отправлен
     * 						Sent - Отправлен
     * 						AutoGenerated - Сформирован автоматически
     * 
     */
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ResponseStatusType responseStatus;
    /**
     * Ответ на подзапрос
     * 
     */
    protected DSRType.ResponseData responseData;

    /**
     * Идентификатор подзапроса, присвоенный в ГИС ЖКХ
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubrequestGUID() {
        return subrequestGUID;
    }

    /**
     * Sets the value of the subrequestGUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getSubrequestGUID()
     */
    public void setSubrequestGUID(String value) {
        this.subrequestGUID = value;
    }

    /**
     * Информация об исходном запросе в ГИС ЖКХ о наличии задолженности за ЖКУ
     * 
     * @return
     *     possible object is
     *     {@link DSRType.RequestInfo }
     *     
     */
    public DSRType.RequestInfo getRequestInfo() {
        return requestInfo;
    }

    /**
     * Sets the value of the requestInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DSRType.RequestInfo }
     *     
     * @see #getRequestInfo()
     */
    public void setRequestInfo(DSRType.RequestInfo value) {
        this.requestInfo = value;
    }

    /**
     * Статус ответа на подзапрос о наличии задолженности за ЖКУ.
     * 
     * 						Допустимые значения:
     * 						NotSent - Не отправлен
     * 						Sent - Отправлен
     * 						AutoGenerated - Сформирован автоматически
     * 
     * @return
     *     possible object is
     *     {@link ResponseStatusType }
     *     
     */
    public ResponseStatusType getResponseStatus() {
        return responseStatus;
    }

    /**
     * Sets the value of the responseStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseStatusType }
     *     
     * @see #getResponseStatus()
     */
    public void setResponseStatus(ResponseStatusType value) {
        this.responseStatus = value;
    }

    /**
     * Ответ на подзапрос
     * 
     * @return
     *     possible object is
     *     {@link DSRType.ResponseData }
     *     
     */
    public DSRType.ResponseData getResponseData() {
        return responseData;
    }

    /**
     * Sets the value of the responseData property.
     * 
     * @param value
     *     allowed object is
     *     {@link DSRType.ResponseData }
     *     
     * @see #getResponseData()
     */
    public void setResponseData(DSRType.ResponseData value) {
        this.responseData = value;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="requestGUID" type="{http://dom.gosuslugi.ru/schema/integration/base/}GUIDType"/>
     *         <element name="requestNumber" type="{http://dom.gosuslugi.ru/schema/integration/drs/}RequestNumberType"/>
     *         <element name="organization" type="{http://dom.gosuslugi.ru/schema/integration/drs/}OrganizationInfoType"/>
     *         <element name="housingFundObject" type="{http://dom.gosuslugi.ru/schema/integration/drs/}ExportHousingFundObjectInfoType"/>
     *         <element name="period" type="{http://dom.gosuslugi.ru/schema/integration/base/}Period"/>
     *         <element name="status" type="{http://dom.gosuslugi.ru/schema/integration/drs/}RequestStatusType"/>
     *         <element name="sentDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         <element name="responseDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         <element name="executorInfo" type="{http://dom.gosuslugi.ru/schema/integration/drs/}ExecutorInfoType"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "requestGUID",
        "requestNumber",
        "organization",
        "housingFundObject",
        "period",
        "status",
        "sentDate",
        "responseDate",
        "executorInfo"
    })
    public static class RequestInfo {

        /**
         * Идентификатор запроса в ГИС ЖКХ
         * 
         */
        @XmlElement(required = true)
        protected String requestGUID;
        /**
         * Номер запроса
         * 
         */
        @XmlElement(required = true)
        protected String requestNumber;
        /**
         * Организация,
         * 									направившая запрос
         * 
         */
        @XmlElement(required = true)
        protected OrganizationInfoType organization;
        /**
         * Объект жилищного фонда (ОЖФ), по которому осуществляется запрос
         * 
         */
        @XmlElement(required = true)
        protected ExportHousingFundObjectInfoType housingFundObject;
        /**
         * Период, за который запрашивается задолженность
         * 
         */
        @XmlElement(required = true)
        protected Period period;
        /**
         * Статус запроса.
         * 
         * 									Допустимые значения:
         * 									Sent - Направлен
         * 									Processed - Получен ответ
         * 
         */
        @XmlElement(required = true)
        @XmlSchemaType(name = "string")
        protected RequestStatusType status;
        /**
         * Дата направления запроса
         * 
         */
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar sentDate;
        /**
         * Крайний срок ответа на запрос
         * 
         */
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar responseDate;
        /**
         * Информация о сотруднике, сформировавшем запрос
         * 
         */
        @XmlElement(required = true)
        protected ExecutorInfoType executorInfo;

        /**
         * Идентификатор запроса в ГИС ЖКХ
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRequestGUID() {
            return requestGUID;
        }

        /**
         * Sets the value of the requestGUID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getRequestGUID()
         */
        public void setRequestGUID(String value) {
            this.requestGUID = value;
        }

        /**
         * Номер запроса
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRequestNumber() {
            return requestNumber;
        }

        /**
         * Sets the value of the requestNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getRequestNumber()
         */
        public void setRequestNumber(String value) {
            this.requestNumber = value;
        }

        /**
         * Организация,
         * 									направившая запрос
         * 
         * @return
         *     possible object is
         *     {@link OrganizationInfoType }
         *     
         */
        public OrganizationInfoType getOrganization() {
            return organization;
        }

        /**
         * Sets the value of the organization property.
         * 
         * @param value
         *     allowed object is
         *     {@link OrganizationInfoType }
         *     
         * @see #getOrganization()
         */
        public void setOrganization(OrganizationInfoType value) {
            this.organization = value;
        }

        /**
         * Объект жилищного фонда (ОЖФ), по которому осуществляется запрос
         * 
         * @return
         *     possible object is
         *     {@link ExportHousingFundObjectInfoType }
         *     
         */
        public ExportHousingFundObjectInfoType getHousingFundObject() {
            return housingFundObject;
        }

        /**
         * Sets the value of the housingFundObject property.
         * 
         * @param value
         *     allowed object is
         *     {@link ExportHousingFundObjectInfoType }
         *     
         * @see #getHousingFundObject()
         */
        public void setHousingFundObject(ExportHousingFundObjectInfoType value) {
            this.housingFundObject = value;
        }

        /**
         * Период, за который запрашивается задолженность
         * 
         * @return
         *     possible object is
         *     {@link Period }
         *     
         */
        public Period getPeriod() {
            return period;
        }

        /**
         * Sets the value of the period property.
         * 
         * @param value
         *     allowed object is
         *     {@link Period }
         *     
         * @see #getPeriod()
         */
        public void setPeriod(Period value) {
            this.period = value;
        }

        /**
         * Статус запроса.
         * 
         * 									Допустимые значения:
         * 									Sent - Направлен
         * 									Processed - Получен ответ
         * 
         * @return
         *     possible object is
         *     {@link RequestStatusType }
         *     
         */
        public RequestStatusType getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link RequestStatusType }
         *     
         * @see #getStatus()
         */
        public void setStatus(RequestStatusType value) {
            this.status = value;
        }

        /**
         * Дата направления запроса
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getSentDate() {
            return sentDate;
        }

        /**
         * Sets the value of the sentDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         * @see #getSentDate()
         */
        public void setSentDate(XMLGregorianCalendar value) {
            this.sentDate = value;
        }

        /**
         * Крайний срок ответа на запрос
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getResponseDate() {
            return responseDate;
        }

        /**
         * Sets the value of the responseDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         * @see #getResponseDate()
         */
        public void setResponseDate(XMLGregorianCalendar value) {
            this.responseDate = value;
        }

        /**
         * Информация о сотруднике, сформировавшем запрос
         * 
         * @return
         *     possible object is
         *     {@link ExecutorInfoType }
         *     
         */
        public ExecutorInfoType getExecutorInfo() {
            return executorInfo;
        }

        /**
         * Sets the value of the executorInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link ExecutorInfoType }
         *     
         * @see #getExecutorInfo()
         */
        public void setExecutorInfo(ExecutorInfoType value) {
            this.executorInfo = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="hasDebt" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         <element name="debtInfo" type="{http://dom.gosuslugi.ru/schema/integration/drs/}ExportDebtInfoType" maxOccurs="unbounded" minOccurs="0"/>
     *         <element name="additionalFile" type="{http://dom.gosuslugi.ru/schema/integration/base/}AttachmentType" maxOccurs="unbounded" minOccurs="0"/>
     *         <element name="description" minOccurs="0">
     *           <simpleType>
     *             <restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               <maxLength value="1000"/>
     *             </restriction>
     *           </simpleType>
     *         </element>
     *         <element name="executorInfo" type="{http://dom.gosuslugi.ru/schema/integration/drs/}ExecutorInfoType"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "hasDebt",
        "debtInfo",
        "additionalFile",
        "description",
        "executorInfo"
    })
    public static class ResponseData {

        /**
         * Признак наличия задолженности, подтвержденной судебным актом
         * 
         */
        protected boolean hasDebt;
        /**
         * Информация о непогашенной задолженности, подтвержденной судебным актом
         * 
         */
        protected List<ExportDebtInfoType> debtInfo;
        /**
         * Дополнительный файл
         * 
         */
        protected List<AttachmentType> additionalFile;
        /**
         * Дополнительная информация
         * 
         */
        protected String description;
        /**
         * Информация о сотруднике, сформировавшем ответ
         * 
         */
        @XmlElement(required = true)
        protected ExecutorInfoType executorInfo;

        /**
         * Признак наличия задолженности, подтвержденной судебным актом
         * 
         */
        public boolean isHasDebt() {
            return hasDebt;
        }

        /**
         * Sets the value of the hasDebt property.
         * 
         */
        public void setHasDebt(boolean value) {
            this.hasDebt = value;
        }

        /**
         * Информация о непогашенной задолженности, подтвержденной судебным актом
         * 
         * Gets the value of the debtInfo property.
         * 
         * <p>This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the debtInfo property.</p>
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * </p>
         * <pre>
         * getDebtInfo().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ExportDebtInfoType }
         * </p>
         * 
         * 
         * @return
         *     The value of the debtInfo property.
         */
        public List<ExportDebtInfoType> getDebtInfo() {
            if (debtInfo == null) {
                debtInfo = new ArrayList<>();
            }
            return this.debtInfo;
        }

        /**
         * Дополнительный файл
         * 
         * Gets the value of the additionalFile property.
         * 
         * <p>This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the additionalFile property.</p>
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * </p>
         * <pre>
         * getAdditionalFile().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AttachmentType }
         * </p>
         * 
         * 
         * @return
         *     The value of the additionalFile property.
         */
        public List<AttachmentType> getAdditionalFile() {
            if (additionalFile == null) {
                additionalFile = new ArrayList<>();
            }
            return this.additionalFile;
        }

        /**
         * Дополнительная информация
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         * @see #getDescription()
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Информация о сотруднике, сформировавшем ответ
         * 
         * @return
         *     possible object is
         *     {@link ExecutorInfoType }
         *     
         */
        public ExecutorInfoType getExecutorInfo() {
            return executorInfo;
        }

        /**
         * Sets the value of the executorInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link ExecutorInfoType }
         *     
         * @see #getExecutorInfo()
         */
        public void setExecutorInfo(ExecutorInfoType value) {
            this.executorInfo = value;
        }

    }

}
