
package ru.gosuslugi.dom.schema.integration.drs;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import ru.gosuslugi.dom.schema.integration.base.BaseType;
import ru.gosuslugi.dom.schema.integration.base.Period;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <extension base="{http://dom.gosuslugi.ru/schema/integration/base/}BaseType">
 *       <sequence>
 *         <choice>
 *           <element name="subrequestGUID" type="{http://dom.gosuslugi.ru/schema/integration/base/}GUIDType" maxOccurs="100"/>
 *           <element name="requestNumber" type="{http://dom.gosuslugi.ru/schema/integration/drs/}RequestNumberType" maxOccurs="100"/>
 *           <sequence>
 *             <element name="periodOfSendingRequest" type="{http://dom.gosuslugi.ru/schema/integration/base/}Period"/>
 *             <choice minOccurs="0">
 *               <element name="houseGUID" type="{http://dom.gosuslugi.ru/schema/integration/base/}GUIDType" maxOccurs="100" minOccurs="0"/>
 *               <element name="exportHMObjectGUID" type="{http://dom.gosuslugi.ru/schema/integration/drs/}ExportHMObjectInfoType" maxOccurs="100" minOccurs="0"/>
 *             </choice>
 *             <element name="requestStatus" type="{http://dom.gosuslugi.ru/schema/integration/drs/}RequestStatusType" minOccurs="0"/>
 *             <element name="responseStatus" type="{http://dom.gosuslugi.ru/schema/integration/drs/}ResponseStatusType" maxOccurs="2" minOccurs="0"/>
 *             <element name="exportSubrequestGUID" type="{http://dom.gosuslugi.ru/schema/integration/base/}GUIDType" minOccurs="0"/>
 *           </sequence>
 *         </choice>
 *         <element name="includeResponses" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       </sequence>
 *       <attribute ref="{http://dom.gosuslugi.ru/schema/integration/base/}version use="required""/>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "subrequestGUID",
    "requestNumber",
    "periodOfSendingRequest",
    "houseGUID",
    "exportHMObjectGUID",
    "requestStatus",
    "responseStatus",
    "exportSubrequestGUID",
    "includeResponses"
})
@XmlRootElement(name = "exportDSRsRequest")
public class ExportDSRsRequest
    extends BaseType
{

    /**
     * Идентификатор подзапроса, сформированного ГИС ЖКХ
     * 
     */
    protected List<String> subrequestGUID;
    /**
     * Номер запроса о наличии задолженности за ЖКУ, направленного в ГИС ЖКХ
     * 
     */
    protected List<String> requestNumber;
    /**
     * Период направления запроса поставщикам ЖКУ.
     * 											Указываемый период не должен превышать 6-ти месяцев
     * 
     */
    protected Period periodOfSendingRequest;
    /**
     * Идентификатор дома в Реестре адресных объектов ГИС ЖКХ, с которым связан запрос о наличии задолженности.
     * Указывается для версии 13.1.10.1
     * 
     */
    protected List<String> houseGUID;
    /**
     * Идентификатор дома/помещения/комнаты в Реестре адресных объектов ГИС ЖКХ и Тип ОЖФ.
     * Указывается для версии 14.0.0.0
     * 
     */
    protected List<ExportHMObjectInfoType> exportHMObjectGUID;
    /**
     * Статус запроса, направленного в ГИС ЖКХ.
     * 
     * 											Допустимые значения:
     * 											Sent - Направлен;
     * 											Processed - Получен ответ
     * 
     */
    @XmlSchemaType(name = "string")
    protected RequestStatusType requestStatus;
    /**
     * Статус ответа на подзапрос, сформированный ГИС ЖКХ.
     * 
     * 											Допустимые значения:
     * 											NotSent - Не отправлен;
     * 											Sent - Отправлен;
     * 											AutoGenerated - Сформирован автоматически
     * 
     */
    @XmlSchemaType(name = "string")
    protected List<ResponseStatusType> responseStatus;
    /**
     * Идентификатор, используемый для экспорта 2-го и последующих блоков данных.
     * 
     * 											Если в элементе exportDSRsRequest указаны условия отбора по атрибутам запроса/подзапроса, то экспорт подзапросов осуществляется блоками по 100 подзапросов в каждом блоке (последний блок может содержать меньшее число подзапросов).
     * 
     * 											Для экспорта первого блока данных элемент не указывается. Для экспорта каждого следующего блока данных в элементе должно указываться значение элемента getStateResult/ exportDSRsResult/ pagedOutput/ nextSubrequestGUID, полученное при экспорте предыдущего блока данных
     * 
     */
    protected String exportSubrequestGUID;
    /**
     * Признак включения в результат сведений об ответах на запросы о задолженности по ЖКУ.
     * Указывается для версии 13.1.10.1
     * 
     */
    protected Boolean includeResponses;
    /**
     * Версия элемента, начиная с которой поддерживается совместимость
     * 
     */
    @XmlAttribute(name = "version", namespace = "http://dom.gosuslugi.ru/schema/integration/base/", required = true)
    protected String version;

    /**
     * Идентификатор подзапроса, сформированного ГИС ЖКХ
     * 
     * Gets the value of the subrequestGUID property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subrequestGUID property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getSubrequestGUID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * </p>
     * 
     * 
     * @return
     *     The value of the subrequestGUID property.
     */
    public List<String> getSubrequestGUID() {
        if (subrequestGUID == null) {
            subrequestGUID = new ArrayList<>();
        }
        return this.subrequestGUID;
    }

    /**
     * Номер запроса о наличии задолженности за ЖКУ, направленного в ГИС ЖКХ
     * 
     * Gets the value of the requestNumber property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requestNumber property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getRequestNumber().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * </p>
     * 
     * 
     * @return
     *     The value of the requestNumber property.
     */
    public List<String> getRequestNumber() {
        if (requestNumber == null) {
            requestNumber = new ArrayList<>();
        }
        return this.requestNumber;
    }

    /**
     * Период направления запроса поставщикам ЖКУ.
     * 											Указываемый период не должен превышать 6-ти месяцев
     * 
     * @return
     *     possible object is
     *     {@link Period }
     *     
     */
    public Period getPeriodOfSendingRequest() {
        return periodOfSendingRequest;
    }

    /**
     * Sets the value of the periodOfSendingRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link Period }
     *     
     * @see #getPeriodOfSendingRequest()
     */
    public void setPeriodOfSendingRequest(Period value) {
        this.periodOfSendingRequest = value;
    }

    /**
     * Идентификатор дома в Реестре адресных объектов ГИС ЖКХ, с которым связан запрос о наличии задолженности.
     * Указывается для версии 13.1.10.1
     * 
     * Gets the value of the houseGUID property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the houseGUID property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getHouseGUID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * </p>
     * 
     * 
     * @return
     *     The value of the houseGUID property.
     */
    public List<String> getHouseGUID() {
        if (houseGUID == null) {
            houseGUID = new ArrayList<>();
        }
        return this.houseGUID;
    }

    /**
     * Идентификатор дома/помещения/комнаты в Реестре адресных объектов ГИС ЖКХ и Тип ОЖФ.
     * Указывается для версии 14.0.0.0
     * 
     * Gets the value of the exportHMObjectGUID property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the exportHMObjectGUID property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExportHMObjectGUID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExportHMObjectInfoType }
     * </p>
     * 
     * 
     * @return
     *     The value of the exportHMObjectGUID property.
     */
    public List<ExportHMObjectInfoType> getExportHMObjectGUID() {
        if (exportHMObjectGUID == null) {
            exportHMObjectGUID = new ArrayList<>();
        }
        return this.exportHMObjectGUID;
    }

    /**
     * Статус запроса, направленного в ГИС ЖКХ.
     * 
     * 											Допустимые значения:
     * 											Sent - Направлен;
     * 											Processed - Получен ответ
     * 
     * @return
     *     possible object is
     *     {@link RequestStatusType }
     *     
     */
    public RequestStatusType getRequestStatus() {
        return requestStatus;
    }

    /**
     * Sets the value of the requestStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestStatusType }
     *     
     * @see #getRequestStatus()
     */
    public void setRequestStatus(RequestStatusType value) {
        this.requestStatus = value;
    }

    /**
     * Статус ответа на подзапрос, сформированный ГИС ЖКХ.
     * 
     * 											Допустимые значения:
     * 											NotSent - Не отправлен;
     * 											Sent - Отправлен;
     * 											AutoGenerated - Сформирован автоматически
     * 
     * Gets the value of the responseStatus property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the responseStatus property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getResponseStatus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResponseStatusType }
     * </p>
     * 
     * 
     * @return
     *     The value of the responseStatus property.
     */
    public List<ResponseStatusType> getResponseStatus() {
        if (responseStatus == null) {
            responseStatus = new ArrayList<>();
        }
        return this.responseStatus;
    }

    /**
     * Идентификатор, используемый для экспорта 2-го и последующих блоков данных.
     * 
     * 											Если в элементе exportDSRsRequest указаны условия отбора по атрибутам запроса/подзапроса, то экспорт подзапросов осуществляется блоками по 100 подзапросов в каждом блоке (последний блок может содержать меньшее число подзапросов).
     * 
     * 											Для экспорта первого блока данных элемент не указывается. Для экспорта каждого следующего блока данных в элементе должно указываться значение элемента getStateResult/ exportDSRsResult/ pagedOutput/ nextSubrequestGUID, полученное при экспорте предыдущего блока данных
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExportSubrequestGUID() {
        return exportSubrequestGUID;
    }

    /**
     * Sets the value of the exportSubrequestGUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getExportSubrequestGUID()
     */
    public void setExportSubrequestGUID(String value) {
        this.exportSubrequestGUID = value;
    }

    /**
     * Признак включения в результат сведений об ответах на запросы о задолженности по ЖКУ.
     * Указывается для версии 13.1.10.1
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludeResponses() {
        return includeResponses;
    }

    /**
     * Sets the value of the includeResponses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #isIncludeResponses()
     */
    public void setIncludeResponses(Boolean value) {
        this.includeResponses = value;
    }

    /**
     * Версия элемента, начиная с которой поддерживается совместимость
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getVersion()
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
