
package ru.gosuslugi.dom.schema.integration.services_service_async;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ServicesServiceAsync", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/services-service-async/", wsdlLocation = "http://localhost/")
public class ServicesServiceAsync
    extends Service
{

    private static final URL SERVICESSERVICEASYNC_WSDL_LOCATION;
    private static final WebServiceException SERVICESSERVICEASYNC_EXCEPTION;
    private static final QName SERVICESSERVICEASYNC_QNAME = new QName("http://dom.gosuslugi.ru/schema/integration/services-service-async/", "ServicesServiceAsync");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICESSERVICEASYNC_WSDL_LOCATION = url;
        SERVICESSERVICEASYNC_EXCEPTION = e;
    }

    public ServicesServiceAsync() {
        super(__getWsdlLocation(), SERVICESSERVICEASYNC_QNAME);
    }

    public ServicesServiceAsync(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICESSERVICEASYNC_QNAME, features);
    }

    public ServicesServiceAsync(URL wsdlLocation) {
        super(wsdlLocation, SERVICESSERVICEASYNC_QNAME);
    }

    public ServicesServiceAsync(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICESSERVICEASYNC_QNAME, features);
    }

    public ServicesServiceAsync(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicesServiceAsync(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicesPortsTypeAsync
     */
    @WebEndpoint(name = "defaultPort")
    public ServicesPortsTypeAsync getDefaultPort() {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/services-service-async/", "defaultPort"), ServicesPortsTypeAsync.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicesPortsTypeAsync
     */
    @WebEndpoint(name = "defaultPort")
    public ServicesPortsTypeAsync getDefaultPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/services-service-async/", "defaultPort"), ServicesPortsTypeAsync.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICESSERVICEASYNC_EXCEPTION!= null) {
            throw SERVICESSERVICEASYNC_EXCEPTION;
        }
        return SERVICESSERVICEASYNC_WSDL_LOCATION;
    }

}
