
package ru.gosuslugi.dom.schema.integration.organizations_registry_common_service_async;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "RegOrgServiceAsync", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/organizations-registry-common-service-async/", wsdlLocation = "http://localhost/")
public class RegOrgServiceAsync
    extends Service
{

    private static final URL REGORGSERVICEASYNC_WSDL_LOCATION;
    private static final WebServiceException REGORGSERVICEASYNC_EXCEPTION;
    private static final QName REGORGSERVICEASYNC_QNAME = new QName("http://dom.gosuslugi.ru/schema/integration/organizations-registry-common-service-async/", "RegOrgServiceAsync");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REGORGSERVICEASYNC_WSDL_LOCATION = url;
        REGORGSERVICEASYNC_EXCEPTION = e;
    }

    public RegOrgServiceAsync() {
        super(__getWsdlLocation(), REGORGSERVICEASYNC_QNAME);
    }

    public RegOrgServiceAsync(WebServiceFeature... features) {
        super(__getWsdlLocation(), REGORGSERVICEASYNC_QNAME, features);
    }

    public RegOrgServiceAsync(URL wsdlLocation) {
        super(wsdlLocation, REGORGSERVICEASYNC_QNAME);
    }

    public RegOrgServiceAsync(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REGORGSERVICEASYNC_QNAME, features);
    }

    public RegOrgServiceAsync(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegOrgServiceAsync(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RegOrgPortsTypeAsync
     */
    @WebEndpoint(name = "RegOrgAsyncPort")
    public RegOrgPortsTypeAsync getRegOrgAsyncPort() {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/organizations-registry-common-service-async/", "RegOrgAsyncPort"), RegOrgPortsTypeAsync.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegOrgPortsTypeAsync
     */
    @WebEndpoint(name = "RegOrgAsyncPort")
    public RegOrgPortsTypeAsync getRegOrgAsyncPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/organizations-registry-common-service-async/", "RegOrgAsyncPort"), RegOrgPortsTypeAsync.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REGORGSERVICEASYNC_EXCEPTION!= null) {
            throw REGORGSERVICEASYNC_EXCEPTION;
        }
        return REGORGSERVICEASYNC_WSDL_LOCATION;
    }

}
