
package ru.gosuslugi.dom.schema.integration.rap_service_async;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import ru.gosuslugi.dom.schema.integration.base.AckRequest;
import ru.gosuslugi.dom.schema.integration.base.GetStateRequest;
import ru.gosuslugi.dom.schema.integration.rap.ExportDecreesAndDocumentsRequest;
import ru.gosuslugi.dom.schema.integration.rap.GetStateResult;
import ru.gosuslugi.dom.schema.integration.rap.ImportDecreesAndDocumentsRequest;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "RapPortAsync", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/rap-service-async/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration.rap.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.organizations_registry_base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.nsi_base.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.individual_registry_base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.organizations_base.ObjectFactory.class
})
public interface RapPortAsync {


    /**
     * Результат обработки асинхронного вызова
     * 
     * @param getStateRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.rap.GetStateResult
     * @throws Fault
     */
    @WebMethod(action = "urn:getState")
    @WebResult(name = "getStateResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/rap/", partName = "getStateResult")
    public GetStateResult getState(
        @WebParam(name = "getStateRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "getStateRequest")
        GetStateRequest getStateRequest)
        throws Fault
    ;

    /**
     * Импорт постановлений и процессуальных документов
     * 
     * @param importDecreesAndDocumentsRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importDecreesAndDocumentsData")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest importDecreesAndDocumentsData(
        @WebParam(name = "ImportDecreesAndDocumentsRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/rap/", partName = "ImportDecreesAndDocumentsRequest")
        ImportDecreesAndDocumentsRequest importDecreesAndDocumentsRequest)
        throws Fault
    ;

    /**
     * Экспорт постановлений и процессуальных документов
     * 
     * @param exportDecreesAndDocumentsRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportDecreesAndDocumentsData")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest exportDecreesAndDocumentsData(
        @WebParam(name = "ExportDecreesAndDocumentsRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/rap/", partName = "ExportDecreesAndDocumentsRequest")
        ExportDecreesAndDocumentsRequest exportDecreesAndDocumentsRequest)
        throws Fault
    ;

}
