
package ru.gosuslugi.dom.schema.integration.tech_conn_service_async;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import ru.gosuslugi.dom.schema.integration.base.AckRequest;
import ru.gosuslugi.dom.schema.integration.base.GetStateRequest;
import ru.gosuslugi.dom.schema.integration.tech_conn.ExportActApplicationRequest;
import ru.gosuslugi.dom.schema.integration.tech_conn.ExportAgreementApplicationRequest;
import ru.gosuslugi.dom.schema.integration.tech_conn.ExportConnectionPossibilityApplicationRequest;
import ru.gosuslugi.dom.schema.integration.tech_conn.ExportOrganizationDeterminationApplicationRequest;
import ru.gosuslugi.dom.schema.integration.tech_conn.ExportTechnicalSpecificationApplicationRequest;
import ru.gosuslugi.dom.schema.integration.tech_conn.GetStateResult;
import ru.gosuslugi.dom.schema.integration.tech_conn.ImportActApplicationStatusRequest;
import ru.gosuslugi.dom.schema.integration.tech_conn.ImportAgreementApplicationStatusRequest;
import ru.gosuslugi.dom.schema.integration.tech_conn.ImportConnectionPossibilityApplicationStatusRequest;
import ru.gosuslugi.dom.schema.integration.tech_conn.ImportOrganizationDeterminationApplicationStatusRequest;
import ru.gosuslugi.dom.schema.integration.tech_conn.ImportTechnicalSpecificationApplicationStatusRequest;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "TechConnPortsTypeAsync", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/tech-conn-service-async/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration.base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.tech_conn.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.nsi_base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.organizations_registry_base.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.organizations_base.ObjectFactory.class
})
public interface TechConnPortsTypeAsync {


    /**
     * Экспорт заявления на определение организации для технологического присоединения
     * 
     * @param exportOrganizationDeterminationApplicationRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportOrganizationDeterminationApplication")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest exportOrganizationDeterminationApplication(
        @WebParam(name = "exportOrganizationDeterminationApplicationRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/tech-conn/", partName = "exportOrganizationDeterminationApplicationRequest")
        ExportOrganizationDeterminationApplicationRequest exportOrganizationDeterminationApplicationRequest)
        throws Fault
    ;

    /**
     * Экспорт заявления на предоставление технических условий подключения
     * 
     * @param exportTechnicalSpecificationApplicationRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportTechnicalSpecificationApplication")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest exportTechnicalSpecificationApplication(
        @WebParam(name = "exportTechnicalSpecificationApplicationRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/tech-conn/", partName = "exportTechnicalSpecificationApplicationRequest")
        ExportTechnicalSpecificationApplicationRequest exportTechnicalSpecificationApplicationRequest)
        throws Fault
    ;

    /**
     * Экспорт заявления на предоставление информации о возможности подключения
     * 
     * @param exportConnectionPossibilityApplicationRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportConnectionPossibilityApplication")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest exportConnectionPossibilityApplication(
        @WebParam(name = "exportConnectionPossibilityApplicationRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/tech-conn/", partName = "exportConnectionPossibilityApplicationRequest")
        ExportConnectionPossibilityApplicationRequest exportConnectionPossibilityApplicationRequest)
        throws Fault
    ;

    /**
     * Экспорт заявления на заключение договора о подключении
     * 
     * @param exportAgreementApplicationRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportAgreementApplication")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest exportAgreementApplication(
        @WebParam(name = "exportAgreementApplicationRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/tech-conn/", partName = "exportAgreementApplicationRequest")
        ExportAgreementApplicationRequest exportAgreementApplicationRequest)
        throws Fault
    ;

    /**
     * Экспорт заявления на получение акта по договору о подключении
     * 
     * @param exportActApplicationRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportActApplication")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest exportActApplication(
        @WebParam(name = "exportActApplicationRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/tech-conn/", partName = "exportActApplicationRequest")
        ExportActApplicationRequest exportActApplicationRequest)
        throws Fault
    ;

    /**
     * Импорт информации об изменении статуса заявления на определение организации для технологического присоединения
     * 
     * @param importOrganizationDeterminationApplicationStatusRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importOrganizationDeterminationApplicationStatus")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest importOrganizationDeterminationApplicationStatus(
        @WebParam(name = "importOrganizationDeterminationApplicationStatusRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/tech-conn/", partName = "importOrganizationDeterminationApplicationStatusRequest")
        ImportOrganizationDeterminationApplicationStatusRequest importOrganizationDeterminationApplicationStatusRequest)
        throws Fault
    ;

    /**
     * Импорт информации об изменении статуса заявления на предоставление технических условий подключения
     * 
     * @param importTechnicalSpecificationApplicationStatusRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importTechnicalSpecificationApplicationStatus")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest importTechnicalSpecificationApplicationStatus(
        @WebParam(name = "importTechnicalSpecificationApplicationStatusRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/tech-conn/", partName = "importTechnicalSpecificationApplicationStatusRequest")
        ImportTechnicalSpecificationApplicationStatusRequest importTechnicalSpecificationApplicationStatusRequest)
        throws Fault
    ;

    /**
     * Импорт информации об изменении статуса заявления на предоставление информации о возможности подключения
     * 
     * @param importConnectionPossibilityApplicationStatusRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importConnectionPossibilityApplicationStatus")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest importConnectionPossibilityApplicationStatus(
        @WebParam(name = "importConnectionPossibilityApplicationStatusRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/tech-conn/", partName = "importConnectionPossibilityApplicationStatusRequest")
        ImportConnectionPossibilityApplicationStatusRequest importConnectionPossibilityApplicationStatusRequest)
        throws Fault
    ;

    /**
     * Импорт информации об изменении статуса заявления на заключение договора о подключении
     * 
     * @param importAgreementApplicationStatusRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importAgreementApplicationStatus")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest importAgreementApplicationStatus(
        @WebParam(name = "importAgreementApplicationStatusRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/tech-conn/", partName = "importAgreementApplicationStatusRequest")
        ImportAgreementApplicationStatusRequest importAgreementApplicationStatusRequest)
        throws Fault
    ;

    /**
     * Импорт информации об изменении статуса заявления на получение акта по договору
     * 
     * @param importActApplicationStatusRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importActApplicationStatus")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest importActApplicationStatus(
        @WebParam(name = "importActApplicationStatusRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/tech-conn/", partName = "importActApplicationStatusRequest")
        ImportActApplicationStatusRequest importActApplicationStatusRequest)
        throws Fault
    ;

    /**
     * 
     * @param getStateRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.tech_conn.GetStateResult
     * @throws Fault
     */
    @WebMethod(action = "urn:getState")
    @WebResult(name = "getStateResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/tech-conn/", partName = "getStateResult")
    public GetStateResult getState(
        @WebParam(name = "getStateRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "getStateRequest")
        GetStateRequest getStateRequest)
        throws Fault
    ;

}
