
package ru.gosuslugi.dom.schema.integration.tech_conn_service_async;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * Асинхронный сервис работы с заявлениями по технологическому присоединению
 * 
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "TechConnServiceAsync", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/tech-conn-service-async/", wsdlLocation = "http://localhost/")
public class TechConnServiceAsync
    extends Service
{

    private static final URL TECHCONNSERVICEASYNC_WSDL_LOCATION;
    private static final WebServiceException TECHCONNSERVICEASYNC_EXCEPTION;
    private static final QName TECHCONNSERVICEASYNC_QNAME = new QName("http://dom.gosuslugi.ru/schema/integration/tech-conn-service-async/", "TechConnServiceAsync");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TECHCONNSERVICEASYNC_WSDL_LOCATION = url;
        TECHCONNSERVICEASYNC_EXCEPTION = e;
    }

    public TechConnServiceAsync() {
        super(__getWsdlLocation(), TECHCONNSERVICEASYNC_QNAME);
    }

    public TechConnServiceAsync(WebServiceFeature... features) {
        super(__getWsdlLocation(), TECHCONNSERVICEASYNC_QNAME, features);
    }

    public TechConnServiceAsync(URL wsdlLocation) {
        super(wsdlLocation, TECHCONNSERVICEASYNC_QNAME);
    }

    public TechConnServiceAsync(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TECHCONNSERVICEASYNC_QNAME, features);
    }

    public TechConnServiceAsync(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TechConnServiceAsync(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TechConnPortsTypeAsync
     */
    @WebEndpoint(name = "TechConnPortAsync")
    public TechConnPortsTypeAsync getTechConnPortAsync() {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/tech-conn-service-async/", "TechConnPortAsync"), TechConnPortsTypeAsync.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TechConnPortsTypeAsync
     */
    @WebEndpoint(name = "TechConnPortAsync")
    public TechConnPortsTypeAsync getTechConnPortAsync(WebServiceFeature... features) {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/tech-conn-service-async/", "TechConnPortAsync"), TechConnPortsTypeAsync.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TECHCONNSERVICEASYNC_EXCEPTION!= null) {
            throw TECHCONNSERVICEASYNC_EXCEPTION;
        }
        return TECHCONNSERVICEASYNC_WSDL_LOCATION;
    }

}
