
package ru.gosuslugi.dom.schema.integration.tariff_service;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import ru.gosuslugi.dom.schema.integration.base.AckRequest;
import ru.gosuslugi.dom.schema.integration.base.GetStateRequest;
import ru.gosuslugi.dom.schema.integration.tariff.ExportCapitalRepairTariffRequest;
import ru.gosuslugi.dom.schema.integration.tariff.ExportMunicipalResourceTariffRequest;
import ru.gosuslugi.dom.schema.integration.tariff.ExportResidentialPremisesMaintenanceRequest;
import ru.gosuslugi.dom.schema.integration.tariff.ExportResidentialPremisesUsageRequest;
import ru.gosuslugi.dom.schema.integration.tariff.ExportSocialNormsRequest;
import ru.gosuslugi.dom.schema.integration.tariff.ExportTariffDifferentiationRequest;
import ru.gosuslugi.dom.schema.integration.tariff.GetStateResult;
import ru.gosuslugi.dom.schema.integration.tariff.ImportCapitalRepairTariffRequest;
import ru.gosuslugi.dom.schema.integration.tariff.ImportMunicipalResourceTariffRequest;
import ru.gosuslugi.dom.schema.integration.tariff.ImportResidentialPremisesMaintenanceRequest;
import ru.gosuslugi.dom.schema.integration.tariff.ImportResidentialPremisesUsageRequest;
import ru.gosuslugi.dom.schema.integration.tariff.ImportSocialNormsRequest;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "TariffAsyncPort", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/tariff-service/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration.base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.tariff.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.organizations_registry_base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.nsi_base.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.organizations_base.ObjectFactory.class
})
public interface TariffAsyncPort {


    /**
     * Результат обработки асинхронного вызова
     * 
     * @param getStateRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.tariff.GetStateResult
     * @throws Fault
     */
    @WebMethod(action = "urn:getState")
    @WebResult(name = "getStateResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/tariff/", partName = "getStateResult")
    public GetStateResult getState(
        @WebParam(name = "getStateRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "getStateRequest")
        GetStateRequest getStateRequest)
        throws Fault
    ;

    /**
     * Импорт информации о социальных нормах потребления электрической энергии
     * 
     * @param importSocialNormsRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importSocialNorms")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "importSocialNormsResult")
    public AckRequest importSocialNorms(
        @WebParam(name = "importSocialNormsRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/tariff/", partName = "importSocialNormsRequest")
        ImportSocialNormsRequest importSocialNormsRequest)
        throws Fault
    ;

    /**
     * Экспорт информации о социальных нормах потребления электрической энергии
     * 
     * @param exportSocialNormsRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportSocialNorms")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "exportSocialNormsResult")
    public AckRequest exportSocialNorms(
        @WebParam(name = "exportSocialNormsRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/tariff/", partName = "exportSocialNormsRequest")
        ExportSocialNormsRequest exportSocialNormsRequest)
        throws Fault
    ;

    /**
     * Импорт информации о размерах платы за содержание жилого помещения
     * 
     * @param importResidentialPremisesMaintenanceRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importResidentialPremisesMaintenance")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "importResidentialPremisesMaintenanceResult")
    public AckRequest importResidentialPremisesMaintenance(
        @WebParam(name = "importResidentialPremisesMaintenanceRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/tariff/", partName = "importResidentialPremisesMaintenanceRequest")
        ImportResidentialPremisesMaintenanceRequest importResidentialPremisesMaintenanceRequest)
        throws Fault
    ;

    /**
     * Экспорт информации о размерах платы за содержание жилого помещения
     * 
     * @param exportResidentialPremisesMaintenanceRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportResidentialPremisesMaintenance")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "exportResidentialPremisesMaintenanceResult")
    public AckRequest exportResidentialPremisesMaintenance(
        @WebParam(name = "exportResidentialPremisesMaintenanceRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/tariff/", partName = "exportResidentialPremisesMaintenanceRequest")
        ExportResidentialPremisesMaintenanceRequest exportResidentialPremisesMaintenanceRequest)
        throws Fault
    ;

    /**
     * Импорт информации о тарифах на оплату коммунальных ресурсов
     * 
     * @param importMunicipalResourceTariffRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importMunicipalResourceTariff")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "importMunicipalResourceTariffResult")
    public AckRequest importMunicipalResourceTariff(
        @WebParam(name = "importMunicipalResourceTariffRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/tariff/", partName = "importMunicipalResourceTariffRequest")
        ImportMunicipalResourceTariffRequest importMunicipalResourceTariffRequest)
        throws Fault
    ;

    /**
     * Экспорт информации о тарифах на оплату коммунальных ресурсов
     * 
     * @param exportMunicipalResourceTariffRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportMunicipalResourceTariff")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "exportMunicipalResourceTariffResult")
    public AckRequest exportMunicipalResourceTariff(
        @WebParam(name = "exportMunicipalResourceTariffRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/tariff/", partName = "exportMunicipalResourceTariffRequest")
        ExportMunicipalResourceTariffRequest exportMunicipalResourceTariffRequest)
        throws Fault
    ;

    /**
     * Импорт информации о минимальных размерах взносов на капитальный ремонт
     * 
     * @param importCapitalRepairTariffRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importCapitalRepairTariff")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "importCapitalRepairTariffResult")
    public AckRequest importCapitalRepairTariff(
        @WebParam(name = "importCapitalRepairTariffRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/tariff/", partName = "importCapitalRepairTariffRequest")
        ImportCapitalRepairTariffRequest importCapitalRepairTariffRequest)
        throws Fault
    ;

    /**
     * Экспорт информации о минимальных размерах взносов на капитальный ремонт
     * 
     * @param exportCapitalRepairTariffRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportCapitalRepairTariff")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "exportCapitalRepairTariffResult")
    public AckRequest exportCapitalRepairTariff(
        @WebParam(name = "exportCapitalRepairTariffRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/tariff/", partName = "exportCapitalRepairTariffRequest")
        ExportCapitalRepairTariffRequest exportCapitalRepairTariffRequest)
        throws Fault
    ;

    /**
     * Импорт информации о размерах платы за пользование жилым помещением
     * 
     * @param importResidentialPremisesUsageRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importResidentialPremisesUsage")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "importResidentialPremisesUsageResult")
    public AckRequest importResidentialPremisesUsage(
        @WebParam(name = "importResidentialPremisesUsageRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/tariff/", partName = "importResidentialPremisesUsageRequest")
        ImportResidentialPremisesUsageRequest importResidentialPremisesUsageRequest)
        throws Fault
    ;

    /**
     * Экспорт информации о размерах платы за пользование жилым помещением
     * 
     * @param exportResidentialPremisesUsageRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportResidentialPremisesUsage")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "exportResidentialPremisesUsageResult")
    public AckRequest exportResidentialPremisesUsage(
        @WebParam(name = "exportResidentialPremisesUsageRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/tariff/", partName = "exportResidentialPremisesUsageRequest")
        ExportResidentialPremisesUsageRequest exportResidentialPremisesUsageRequest)
        throws Fault
    ;

    /**
     * Экспорт списка критериев дифференциации
     * 
     * @param exportTariffDifferentiationRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportTariffDifferentiation")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "exportTariffDifferentiationResult")
    public AckRequest exportTariffDifferentiation(
        @WebParam(name = "exportTariffDifferentiationRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/tariff/", partName = "exportTariffDifferentiationRequest")
        ExportTariffDifferentiationRequest exportTariffDifferentiationRequest)
        throws Fault
    ;

}
