
package ru.gosuslugi.dom.schema.integration.tariff_service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * Сервис Ведение тарифов
 * 
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "TariffAsyncService", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/tariff-service/", wsdlLocation = "http://localhost/")
public class TariffAsyncService
    extends Service
{

    private static final URL TARIFFASYNCSERVICE_WSDL_LOCATION;
    private static final WebServiceException TARIFFASYNCSERVICE_EXCEPTION;
    private static final QName TARIFFASYNCSERVICE_QNAME = new QName("http://dom.gosuslugi.ru/schema/integration/tariff-service/", "TariffAsyncService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TARIFFASYNCSERVICE_WSDL_LOCATION = url;
        TARIFFASYNCSERVICE_EXCEPTION = e;
    }

    public TariffAsyncService() {
        super(__getWsdlLocation(), TARIFFASYNCSERVICE_QNAME);
    }

    public TariffAsyncService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TARIFFASYNCSERVICE_QNAME, features);
    }

    public TariffAsyncService(URL wsdlLocation) {
        super(wsdlLocation, TARIFFASYNCSERVICE_QNAME);
    }

    public TariffAsyncService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TARIFFASYNCSERVICE_QNAME, features);
    }

    public TariffAsyncService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TariffAsyncService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TariffAsyncPort
     */
    @WebEndpoint(name = "TariffAsyncPort")
    public TariffAsyncPort getTariffAsyncPort() {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/tariff-service/", "TariffAsyncPort"), TariffAsyncPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TariffAsyncPort
     */
    @WebEndpoint(name = "TariffAsyncPort")
    public TariffAsyncPort getTariffAsyncPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/tariff-service/", "TariffAsyncPort"), TariffAsyncPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TARIFFASYNCSERVICE_EXCEPTION!= null) {
            throw TARIFFASYNCSERVICE_EXCEPTION;
        }
        return TARIFFASYNCSERVICE_WSDL_LOCATION;
    }

}
