
package ru.gosuslugi.dom.schema.integration.rvuo_service_async;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import ru.gosuslugi.dom.schema.integration.base.AckRequest;
import ru.gosuslugi.dom.schema.integration.base.GetStateRequest;
import ru.gosuslugi.dom.schema.integration.rvuo.ExportDecisionRequest;
import ru.gosuslugi.dom.schema.integration.rvuo.ExportManagingOrganizationRequest;
import ru.gosuslugi.dom.schema.integration.rvuo.GetStateResult;
import ru.gosuslugi.dom.schema.integration.rvuo.ImportDecisionRequest;
import ru.gosuslugi.dom.schema.integration.rvuo.ImportManagingOrganizationRequest;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "RvuoPortsTypeAsync", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/rvuo-service-async/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration.rvuo.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.nsi_base.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.organizations_base.ObjectFactory.class
})
public interface RvuoPortsTypeAsync {


    /**
     * Импорт информации об управляющей организации в реестр управляющих организаций и решений об определении управляющих организаций
     * 
     * @param importManagingOrganizationRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importManagingOrganization")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest importManagingOrganization(
        @WebParam(name = "importManagingOrganizationRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/rvuo/", partName = "importManagingOrganizationRequest")
        ImportManagingOrganizationRequest importManagingOrganizationRequest)
        throws Fault
    ;

    /**
     * Импорт информации о решении об определении управляющей организации в реестр управляющих организаций и решений об определении управляющих организаций
     * 
     * @param importDecisionRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importDecision")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest importDecision(
        @WebParam(name = "importDecisionRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/rvuo/", partName = "importDecisionRequest")
        ImportDecisionRequest importDecisionRequest)
        throws Fault
    ;

    /**
     * Получить статус обработки запроса
     * 
     * @param getRequestState
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.rvuo.GetStateResult
     * @throws Fault
     */
    @WebMethod(action = "urn:getState")
    @WebResult(name = "getStateResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/rvuo/", partName = "getRequestStateResult")
    public GetStateResult getState(
        @WebParam(name = "getStateRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "getRequestState")
        GetStateRequest getRequestState)
        throws Fault
    ;

    /**
     * Экспорт информации об управляющих организациях из реестра управляющих организаций и решений об определении управляющих организаций
     * 
     * @param exportManagingOrganizationRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportManagingOrganization")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest exportManagingOrganization(
        @WebParam(name = "exportManagingOrganizationRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/rvuo/", partName = "exportManagingOrganizationRequest")
        ExportManagingOrganizationRequest exportManagingOrganizationRequest)
        throws Fault
    ;

    /**
     * Экспорт информации о решении об определении управляющей организации из реестра управляющих организаций и решений об определении управляющих организаций
     * 
     * @param exportDecisionRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportDecision")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest exportDecision(
        @WebParam(name = "exportDecisionRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/rvuo/", partName = "exportDecisionRequest")
        ExportDecisionRequest exportDecisionRequest)
        throws Fault
    ;

}
