
package ru.gosuslugi.dom.schema.integration.inspection_service_async;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import ru.gosuslugi.dom.schema.integration.base.AckRequest;
import ru.gosuslugi.dom.schema.integration.base.GetStateRequest;
import ru.gosuslugi.dom.schema.integration.inspection.ExportExaminationURIStateRequest;
import ru.gosuslugi.dom.schema.integration.inspection.ExportExaminationsRequest;
import ru.gosuslugi.dom.schema.integration.inspection.ExportInspectionPlansRequest;
import ru.gosuslugi.dom.schema.integration.inspection.GetStateResult;
import ru.gosuslugi.dom.schema.integration.inspection.ImportExaminationsRequest;
import ru.gosuslugi.dom.schema.integration.inspection.ImportInspectionPlanRequest;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "InspectionPortsTypeAsync", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/inspection-service-async/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration.base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.inspection.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.nsi_base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.organizations_registry_base.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.organizations_base.ObjectFactory.class
})
public interface InspectionPortsTypeAsync {


    /**
     * ВИ_ПИЖФ_ИПП. Импорт плана проверок.
     * 
     * @param importInspectionPlanRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importInspectionPlan")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest importInspectionPlan(
        @WebParam(name = "importInspectionPlanRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/inspection/", partName = "importInspectionPlanRequest")
        ImportInspectionPlanRequest importInspectionPlanRequest)
        throws Fault
    ;

    /**
     * ВИ_ПИЖФ_ЭПП. Экспорт плана проверок.
     * 
     * @param exportInspectionPlansRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportInspectionPlans")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest exportInspectionPlans(
        @WebParam(name = "exportInspectionPlansRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/inspection/", partName = "exportInspectionPlansRequest")
        ExportInspectionPlansRequest exportInspectionPlansRequest)
        throws Fault
    ;

    /**
     * ВИ_ПИЖФ_ИП. Импорт проверок.
     * 
     * @param importExaminationsRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importExaminations")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest importExaminations(
        @WebParam(name = "importExaminationsRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/inspection/", partName = "importExaminationsRequest")
        ImportExaminationsRequest importExaminationsRequest)
        throws Fault
    ;

    /**
     * ВИ_ПИЖФ_ЭП. Экспорт проверок.
     * 
     * @param exportExaminationsRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportExaminations")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest exportExaminations(
        @WebParam(name = "exportExaminationsRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/inspection/", partName = "exportExaminationsRequest")
        ExportExaminationsRequest exportExaminationsRequest)
        throws Fault
    ;

    /**
     * 
     * @param getStateRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.inspection.GetStateResult
     * @throws Fault
     */
    @WebMethod(action = "urn:getState")
    @WebResult(name = "getStateResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/inspection/", partName = "getStateResult")
    public GetStateResult getState(
        @WebParam(name = "getStateRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "getStateRequest")
        GetStateRequest getStateRequest)
        throws Fault
    ;

    /**
     * ВИ_ПИЖФ_ЭСП. Экспорт статуса размещения проверок из ЕРП
     * 
     * @param exportExaminationURIStateRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportExaminationURIState")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest exportExaminationURIState(
        @WebParam(name = "exportExaminationURIStateRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/inspection/", partName = "exportExaminationURIStateRequest")
        ExportExaminationURIStateRequest exportExaminationURIStateRequest)
        throws Fault
    ;

}
