
package ru.gosuslugi.dom.schema.integration.debts_async;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import ru.gosuslugi.dom.schema.integration.base.AckRequest;
import ru.gosuslugi.dom.schema.integration.base.GetStateRequest;
import ru.gosuslugi.dom.schema.integration.debts.ExportDebtRequest;
import ru.gosuslugi.dom.schema.integration.debts.GetStateResult;
import ru.gosuslugi.dom.schema.integration.debts.ImportDebtRequest;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "DebtPortsTypeAsync", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/debts-async/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration.debts.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.nsi_base.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.organizations_base.ObjectFactory.class
})
public interface DebtPortsTypeAsync {


    /**
     * Импорт о сведений о задолженностях за ЖКУ
     * 
     * @param importDebtRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importDebt")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest importDebt(
        @WebParam(name = "importDebtRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/debts/", partName = "importDebtRequest")
        ImportDebtRequest importDebtRequest)
        throws Fault
    ;

    /**
     * Экспорт сведений о задолженностях за ЖКУ
     * 
     * @param exportDebtRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportDebt")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest exportDebt(
        @WebParam(name = "exportDebtRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/debts/", partName = "exportDebtRequest")
        ExportDebtRequest exportDebtRequest)
        throws Fault
    ;

    /**
     * Получение статуса обработки запроса
     * 
     * @param getRequestState
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.debts.GetStateResult
     * @throws Fault
     */
    @WebMethod(action = "urn:getState")
    @WebResult(name = "getStateResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/debts/", partName = "getRequestStateResult")
    public GetStateResult getState(
        @WebParam(name = "getStateRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "getRequestState")
        GetStateRequest getRequestState)
        throws Fault
    ;

}
