
package ru.gosuslugi.dom.schema.integration.payment_service_async;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "PaymentsServiceAsync", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/payment-service-async/", wsdlLocation = "http://localhost/")
public class PaymentsServiceAsync
    extends Service
{

    private static final URL PAYMENTSSERVICEASYNC_WSDL_LOCATION;
    private static final WebServiceException PAYMENTSSERVICEASYNC_EXCEPTION;
    private static final QName PAYMENTSSERVICEASYNC_QNAME = new QName("http://dom.gosuslugi.ru/schema/integration/payment-service-async/", "PaymentsServiceAsync");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAYMENTSSERVICEASYNC_WSDL_LOCATION = url;
        PAYMENTSSERVICEASYNC_EXCEPTION = e;
    }

    public PaymentsServiceAsync() {
        super(__getWsdlLocation(), PAYMENTSSERVICEASYNC_QNAME);
    }

    public PaymentsServiceAsync(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAYMENTSSERVICEASYNC_QNAME, features);
    }

    public PaymentsServiceAsync(URL wsdlLocation) {
        super(wsdlLocation, PAYMENTSSERVICEASYNC_QNAME);
    }

    public PaymentsServiceAsync(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAYMENTSSERVICEASYNC_QNAME, features);
    }

    public PaymentsServiceAsync(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentsServiceAsync(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PaymentPortsTypeAsync
     */
    @WebEndpoint(name = "PaymentPortAsync")
    public PaymentPortsTypeAsync getPaymentPortAsync() {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/payment-service-async/", "PaymentPortAsync"), PaymentPortsTypeAsync.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentPortsTypeAsync
     */
    @WebEndpoint(name = "PaymentPortAsync")
    public PaymentPortsTypeAsync getPaymentPortAsync(WebServiceFeature... features) {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/payment-service-async/", "PaymentPortAsync"), PaymentPortsTypeAsync.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAYMENTSSERVICEASYNC_EXCEPTION!= null) {
            throw PAYMENTSSERVICEASYNC_EXCEPTION;
        }
        return PAYMENTSSERVICEASYNC_WSDL_LOCATION;
    }

}
